### ISSUE TITLE
eventBus遇到的问题

### ISSUE THREAD

**Issue by OneLeafAlex** [BolexLiu/AndroidDevHelp#4]
清单文件注册了广播：监听网络状态，发送给服务
 EventBus.getDefault().postSticky(new MessageEvent(NET_OK));

在onHandleIntent设值了一样定时启动的闹钟
  AlarmManager alarmManager = (AlarmManager) getSystemService(ALARM_SERVICE);
        int startingTime = Integer.parseInt(uploadTime) * 1000;//默认30秒
        long triggerTime = SystemClock.elapsedRealtime() + startingTime;
        Intent startService = new Intent(this, UploadIntentService.class);

        PendingIntent pendingIntent = PendingIntent.getService(this, 0, startService, 0);
        alarmManager.set(AlarmManager.ELAPSED_REALTIME_WAKEUP, triggerTime, pendingIntent);

但是看打印：消息也会发送多次随着服务的启动。正常来说，服务的启动不应该会影响这个消息多次发送，消息源只发送了一次消息。在接收这里确接收到和服务定时一样，每隔30s就收到一个消息。
10-17 11:32:44.674 1343-1614/android.car.app.file_upload I/UploadIntentService: onResultCodeEvent   NET_OK
10-17 11:33:14.698 1343-1614/android.car.app.file_upload I/UploadIntentService: onResultCodeEvent   NET_OK
10-17 11:33:44.721 1343-1614/android.car.app.file_upload I/UploadIntentService: onResultCodeEvent   NET_OK
10-17 11:34:14.742 1343-1614/android.car.app.file_upload I/UploadIntentService: onResultCodeEvent   NET_OK
10-17 11:34:44.762 1343-1614/android.car.app.file_upload I/UploadIntentService: onResultCodeEvent   NET_OK
10-17 11:35:14.782 1343-1614/android.car.app.file_upload I/UploadIntentService: onResultCodeEvent   NET_OK

**Comment by BolexLiu** [comment]
把详细代码贴出来。整个的。

**Comment by OneLeafAlex** [comment]
`清单文件静态注册的广播：
public class BootBroadcastReceiver extends BroadcastReceiver {

    //  开机广播：  ACTION_BOOT_COMPLETED
    public static final String TAG = "BootBroadcastReceiver";
    public Context mContext;
    public double mLastTime;

    public BootBroadcastReceiver() {
        Log.i(TAG, "BootBroadcastReceiver  （）");
    }

    public void onReceive(Context context, Intent intent) {

        this.mContext = context;

        Log.i(TAG, "onReceive   action=" + intent.getAction());


        switch (intent.getAction()) {

            case ACTION_BOOT_COMPLETED:
                Log.i(TAG, "onReceive   ACTION_BOOT_COMPLETED   开机了,准备启动服务.....");


                onBootCompleted();
   
                break;
            case ConnectivityManager.CONNECTIVITY_ACTION:
                Log.i(TAG, "onReceive   CONNECTIVITY_ACTION");


                onConnectivityChanged(intent);
                break;

            default:
                break;

        }
    }

    public void onBootCompleted() {
        Log.i(TAG, "onBootCompleted: ");


        startServiceWithExtra();

        EventBus.getDefault().postSticky(new MessageEvent(STARTING_UP));

    }

    public void startServiceWithExtra() {

        Log.i(TAG, "startServiceWithExtra:   start   UploadService");

        Intent intent = new Intent(mContext, UploadIntentService.class);
        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        mContext.startService(intent);

    }


    public void onConnectivityChanged(Intent intent) {

        ConnectivityManager connectMgr = (ConnectivityManager) mContext.getSystemService(CONNECTIVITY_SERVICE);

        if (connectMgr != null) {
            NetworkInfo info = intent.getParcelableExtra(ConnectivityManager.EXTRA_NETWORK_INFO);
            Log.i(TAG, "onConnectivityChanged: NetworkInfo=" + info);

            if (info != null) {
                if (NetworkInfo.State.CONNECTED == info.getState() && info.isAvailable()) {
                    if (info.getType() == ConnectivityManager.TYPE_MOBILE || info.getType() == ConnectivityManager.TYPE_WIFI) {
                        double currentTime = SystemClock.uptimeMillis();
                        if (currentTime - mLastTime < 1000) {
                            Log.i(TAG, "onConnectivityChanged: changed too fast ignore");

                            mLastTime = currentTime;
                            return;
                        }

                        Log.i(TAG, "onConnectivityChanged: 网络连接成功:" + info.getTypeName());


                        EventBus.getDefault().postSticky(new MessageEvent(NET_OK));
                    }
                } else {
                    Log.i(TAG, "onConnectivityChanged: 网络断开:" + info.getTypeName());


                    EventBus.getDefault().postSticky(new MessageEvent(NET_ERROR));
                }
            }
        }

    }
}
`

`-----------------------------------------------------------------------------------------------

service:
public class UploadIntentService extends IntentService {

		protected void onHandleIntent(Intent intent) {
		
		//upLoad   work
		
		//设置再次启动service的时间间隔
		 setStartingUpTime();
		
		}


	    public void setStartingUpTime(String uploadTime) {


        AlarmManager alarmManager = (AlarmManager) getSystemService(ALARM_SERVICE);
        int startingTime = Integer.parseInt(uploadTime) * 1000;//默认30秒
        long triggerTime = SystemClock.elapsedRealtime() + startingTime;
        Intent startService = new Intent(this, UploadIntentService.class);

        PendingIntent pendingIntent = PendingIntent.getService(this, 0, startService, 0);
        alarmManager.set(AlarmManager.ELAPSED_REALTIME_WAKEUP, triggerTime, pendingIntent);

    }
	
	
	@Subscribe(threadMode = ThreadMode.BACKGROUND, sticky = true)
    public void onResultCodeEvent(MessageEvent messageEvent) {
		switch (messageEvent.getResultCode()) {
		    case NET_OK:
                //网络已经连接
                Log.i(TAG, "onResultCodeEvent   NET_OK");//会收到多次


                break;
            case NET_ERROR:
                //无网络
                Log.i(TAG, "onResultCodeEvent   NET_ERROR");

                break;
		}
	}
}`

`-----------------------------------------------------------------------------------------------

MessageEvent:
public class MessageEvent{

    public String message;
    public int resultCode;
    public FileCompressor.CompressResult compressResult;


    public MessageEvent(String message) {
        this.message = message;
    }

    public MessageEvent(int resultCode) {
        this.resultCode = resultCode;
    }

    public MessageEvent(FileCompressor.CompressResult compressResult) {
        this.compressResult = compressResult;
    }


    public String getMessage() {
        return message;
    }

    public int getResultCode() {
        return resultCode;
    }

    public FileCompressor.CompressResult getCompressResult() {
        return compressResult;
    }
}`

**Comment by BolexLiu** [comment]
## 问题的原因
 AlarmManager的Intent逻辑有问题。PendingIntent不应该启动UploadIntentService；
 你现在这样写就是一个递归死循环的在启动多个UploadIntentService组件。
而EventBus.getDefault().postSticky(new MessageEvent(NET_OK)); 这样发是会发送给你起来的多个重复的UploadIntentService组件上。

## 解决办法
1.你现在可以这样改，把PendingIntent换成广播。而不是启动服务。
2.系统的去学习AlarmManager可以启动那些组件。（广播、服务、活动）

**Comment by OneLeafAlex** [comment]
把PendingIntent换成广播是啥意思？是这样吗？
PendingIntent pendingIntentPendingIntent.getBroadcast(this, 0, startService, 0);

**Comment by BolexLiu** [comment]
你的问题是AlarmManager死循环的在启动UploadIntentService组件。
所以不要再启动该组件了。明白了吗？
PendingIntent就是指AlarmManager未来需要启动的意图。将这个意图换成你要接受的广播。而不是服务。

**Comment by OneLeafAlex** [comment]
恩。可我的目的就是开机启动服务，执行了一些上传操作之后，结束服务。然后我想在指定的时间间隔再启动服务。

**Comment by BolexLiu** [comment]
那你不应该用postSticky，或者你考虑注销。

**Comment by OneLeafAlex** [comment]
不用postSticky的话，我试了，服务那边会接收不到。注销？eventBus吗？你的意思是说在执行操作结束把eventBus注销吗？

**Comment by BolexLiu** [comment]
EventBus.getDefault().removeStickyEvent(event);

**Comment by OneLeafAlex** [comment]
那注销了，之后如果网络状态变化了，是不是就接收不到了。

**Comment by OneLeafAlex** [comment]
鸡排，其实我就是想实现一个定时上传文件的service.在文件全部上传完毕后结束服务。然后又在指定的时间再次起来。能给我讲讲思路吗？我现在做的有点乱了。

**Comment by BolexLiu** [comment]
换一个思路的化，我假设你这个上传是比较频繁的。那么你不要把service关闭。让service一直存活。当需要发送消息时利用eventbus推一条消息过去执行就行了。


如果你一定要关掉这个service，那么就在广播收到消息后启动它，而不是用AlarmManager来定时。因为很有可能你上一个组件还未被回收，下一个又被创建了。

**Comment by OneLeafAlex** [comment]
你是说用AlarmManage定时发送一个广播消息，广播接收到了这个消息之后启动这个服务。是这个意思吗？

**Comment by BolexLiu** [comment]
你想想如果不用AlarmManage怎么实现你的这个需求吧。按照我的思路你这样的需要根本不需要AlarmManage和service。

**Comment by OneLeafAlex** [comment]
你能再详细讲讲如果我要关掉这个service，应该怎么实现吗？我是这么想的，如果不用AlarmManage的话，服务很有可能被杀死，而且在休眠之后更有可能会被杀死。

**Comment by BolexLiu** [comment]
你这个应用在后台和关屏幕状态下也要考虑上传吗？

**Comment by OneLeafAlex** [comment]
领导叫我做成一个服务运行在后台定时上传文件，文件上传成功结束服务。要在指定时间启动服务，上传文件…这样循环下去。休眠的时候目前不上传的。

**Comment by BolexLiu** [comment]
这里的指定的时间是由谁来指定，是具体时间。还是间隔时间。

**Comment by OneLeafAlex** [comment]
是指间隔时间。

**Comment by BolexLiu** [comment]
那么我觉得你可以在服务关闭的时候启动下一组定时任务。 而不是放在服务启动时。

**Comment by BolexLiu** [comment]
实际上最近我的工作上也在做类似这种东西。
我封装了一套定时任务队列的框架简单来说只需要这样使用就可以满足需求了。比如
## 第一种： 定时任务
```java
//配置一下你的时间
Tasks.setSartTime("2017-10-17 13:24:55");
Tasks.setSartTime("2017-10-17 15:50:22");
Tasks.setSartTime("2017-10-17 18:55:01");

TimeLooper.with(Tasks).addHandlerMedia(new TimeLooper.TimeHnadler() {
            @Override
            public void exeTask(Task mTask) {
                //到时间的时候会执行该方法，在此处回掉 
            }
        }).startLooperTask();

```

## 第二种： 间隔任务
```java
Tasks.setIntervalTime(3000); //3秒一次 重复执行
TimeLooper.with(Tasks).addHandlerMedia(new TimeLooper.TimeHnadler() {
            @Override
            public void exeTask(Task mTask) {
             //到时间的时候会执行该方法，在此处回掉 
            }
        }).startLooperTask();
```

这套框架，我现在还没有开源出来。后续可能会开源。上面是使用方法。
里面的底层实现也是依赖于AlarmManage。但是会比AlarmManage的使用简单很多。

**Comment by OneLeafAlex** [comment]
哇咔咔，期待啊！到时候你可以把这个功能从你项目中独立出来，然后配上一个demo，完美了，哈哈哈！到时候我可以根据你这个来完善一下。鸡排赶紧搞出来，第一个给你点赞！

**Comment by OneLeafAlex** [comment]
对了，鸡排，就是intentService里面的onHandleIntent方法，如果我把下载文件和上传文件都放这个方法里面，假如我要下载2个文件，上传3个文件，那这样是开了2个线程吗？还是5个？

**Comment by BolexLiu** [comment]
@Alice19940706  https://github.com/BolexLiu/TimeTask
项目已开源。供你参考。
