### ISSUE TITLE
so重复导致的冲突问题

### ISSUE THREAD

**Issue by liujia95** [BolexLiu/AndroidDevHelp#5]
## 我期望的结果：
我想编译通过让程序正确运行。
## 我做了什么：
![](https://user-images.githubusercontent.com/16263630/31766476-42518a62-b4fa-11e7-86a8-9833d663fffa.png)
首先是报的是这个错误，说的好像是3dmap的jar和release/jni某个文件重复导致冲突了。
然后我在网上找到了这个解决方案：
![](https://user-images.githubusercontent.com/16263630/31766604-9e2fa4b8-b4fa-11e7-8e33-53202531f645.png)
他给出一个示例代码，现在我不知道这段示例代码该写在哪里，上面说的是写在app.gradle里面，但是我在里面每个位置都试过了，编译不通过。
## 结果是：
![](https://user-images.githubusercontent.com/16263630/31766784-3efc33c0-b4fb-11e7-9f37-4da4b1139c96.png)
## 工作环境：
- 编译sdk：25.0.2
- java版本：1.8
- 平台：win7
- ide：androidStudio 3.0
- Gradle： 4.1

**Comment by BolexLiu** [comment]
把你的工程结构发上来方便吗？task按理来说不会这样，应该是你写错了什么，或则没放对位置。

**Comment by BolexLiu** [comment]
解决了吗？

**Comment by liujia95** [comment]
还没呢，我换了另一种实现方式，所以这个问题暂时搁置了。。

**Comment by BolexLiu** [comment]
http://www.jianshu.com/p/a3460500a8bb   看下这个有没有用。

**Comment by liujia95** [comment]
谢谢，我看了，是篇好文，但是可能在这个问题下不适用，因为这个问题描述的是：编译中会先合并两个moudle（app和library）的compile配置，然后app中还有个task，这个task又会将该moudle的jni再做一次merge（这一步很迷），导致了重复引用so的问题。跟你那篇文章的（A-->App，B-->App）结构不一样，这个问题的结构更像是（A-->App，A-->App）导致的冲突，我后来找了一种把library中的引用3map的compile改为provided，貌似能解决，但引发了一些其他的问题，后面由于时间紧迫，我最终采取的方式是把library的代码全部copy到了app中。唉。所以这个问题到底是解决了嘛还是没解决我也说不清。。

**Comment by BolexLiu** [comment]
app里面的task会跟随编译执行的化，你这个app里的代码是依赖的源码还是一个库？如果是源码的话，我想你可以直接注释掉吧。
